default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: btp_developement

test:
  <<: *default
  database: btp_test

production:
  <<: *default
  database: btp_production